### ISSUE TITLE
Messages combined into one message in sumo logic when using json layout

### ISSUE THREAD

**Issue by chenliangde** [SumoLogic/sumologic-logback-appender#10]
I have logback config like this: ```    <appender name="SumoAppender" class="com.sumologic.logback.SumoLogicAppender">

        <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
            <layout class="ch.qos.logback.contrib.json.classic.JsonLayout">
                <timestampFormat>yyyy-MM-dd'T'HH:mm:ss.SSSX</timestampFormat>
                <timestampFormatTimezoneId>Etc/UTC</timestampFormatTimezoneId>
                <jsonFormatter class="ch.qos.logback.contrib.jackson.JacksonJsonFormatter">
                    <prettyPrint>true</prettyPrint>
                </jsonFormatter>
            </layout>
        </encoder>
        <messagesPerRequest>50</messagesPerRequest>
        <maxFlushIntervalMs>100</maxFlushIntervalMs>
        <flushingAccuracyMs>10</flushingAccuracyMs>
        <url>....</url>
    </appender>```

And the messages are grouped into one message in sumo logic.  Could you please help?

**Comment by rvmiller89** [comment]
Hi @chenliangde , please try adding the following parameter to your layout:
```
<appendLineSeparator>true</appendLineSeparator>
```
I have updated the example in https://github.com/SumoLogic/sumologic-logback-appender/blob/master/src/test/resources/logback.xml#L61 as well.
