### ISSUE TITLE
JSON support

### ISSUE THREAD

**Issue by tim-terry-otm** [SumoLogic/sumologic-logback-appender#2]
Are there any plans to support JSON log messages? As other hosted logging i can send MDC structured data together with my log message that can be searched upon. Would be handy to do something like this:
`
<encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
            <layout class="ch.qos.logback.contrib.json.classic.JsonLayout">
                <timestampFormat>yyyy-MM-dd'T'HH:mm:ss.SSSX</timestampFormat>
                <timestampFormatTimezoneId>Etc/UTC</timestampFormatTimezoneId>
            </layout>
        </encoder>
`
Instead of using the PatternLayoutEncoder.
Do you accept pull requests?

Regards

**Comment by rvmiller89** [comment]
Resolved in https://github.com/SumoLogic/sumologic-logback-appender/pull/3.  Thanks!
