### ISSUE TITLE
Can't use environment variables for URL

### ISSUE THREAD

**Issue by soneil123** [SumoLogic/sumologic-logback-appender#7]
My company disallows writing tokens/secrets to disk.  If I set an environment variable for the SumoLogic URL in the logback.xml (`<url>${SUMOLOGIC_URL}</url>`), and that variable is unset, an empty string gets passed to the httpClient library resulting in an error: `Caused by: org.apache.http.ProtocolException: Target host is not specified`.

We don't want metrics/logs to be pushed for local/pipeline builds since we aren't allowed to pull the 'secret' out of the environment security zone so the SUMOLOGIC_URL won't be set in certain cases.  Other logging/metric libraries we use will just fail silently or with an INFO message if the URL/API_KEY isn't set.  They also support an enabled/disabled property to shut off logging with a flag.

At a minimum, could the env variable/empty string issue be fixed - and - could a null/empty value for URL be reported as an info (non-failing) response?  The current work-around given is to set `<flushAllBeforeStopping>` to false which isn't ideal since we could lose logs.

**Comment by rvmiller89** [comment]
Fixed in https://github.com/SumoLogic/sumologic-logback-appender/pull/8 (release version 1.3).
